// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1) {
  return window['go']['main']['App']['DecryptFile'](arg1);
}

export function EncryptFile(arg1) {
  return window['go']['main']['App']['EncryptFile'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}
