// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1:string):Promise<boolean>;

export function EncryptFile(arg1:string):Promise<boolean>;

export function SelectFile(arg1:number):Promise<string>;
